

services:
  frontend:
    build: .
    container_name: devportfolio_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - devportfolio_net
    restart: unless-stopped

networks:
  devportfolio_net:
    driver: bridge
