apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 443 ssl;
      server_name localhost;

      ssl_certificate ssl/tls.crt;
      ssl_certificate_key ssl/tls.key;

      location / {
          root /usr/share/nginx/html;
          try_files $uri /index.html;
      }
    }

    server {
      listen 80;
      server_name localhost;
      return 301 https://$host$request_uri;
    }
