name: Deploy to Kubernetes

on:
  push:
    branches: [ master ] # Or use 'master' if your branch is called that

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.mariyam1221 }}" | docker login -u "${{ secrets.tbiruh1221 }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.tbiruh1221 }}/devportfolio:latest .
          docker push ${{ secrets.tbiruh1221 }}/devportfolio:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
